"""autogenerate vote table

Revision ID: 5852a6d5f882
Revises: beda4ed7ffa1
Create Date: 2023-07-30 21:57:29.663709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5852a6d5f882'
down_revision = 'beda4ed7ffa1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
